# Generated by Django 5.1.1 on 2024-09-27 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'tcategoria',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('numero_telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_casa', models.CharField(blank=True, max_length=10, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'tcliente',
            },
        ),
        migrations.CreateModel(
            name='UsuarioAdm',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=255)),
                ('numero_telefone', models.CharField(max_length=15)),
                ('logradouro', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Usuário Administrador',
                'verbose_name_plural': 'Usuários Administradores',
                'db_table': 'tusuarioadm',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('numero_pedido', models.CharField(max_length=255)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('situacao', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='meu_app.cliente')),
                ('cod_usuario_adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='meu_app.usuarioadm')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'tpedido',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='meu_app.categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'tproduto',
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cod_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='meu_app.pedido')),
                ('cod_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='meu_app.produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'db_table': 'tpedidoitem',
            },
        ),
    ]
